# Generated by Django 4.2.7 on 2023-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=20)),
                ("time", models.CharField(max_length=20)),
                ("discipline", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=100)),
                ("groups", models.JSONField()),
            ],
        ),
    ]
